---
version: "2"

volumes:

  elasticsearch_data:
    driver: "local"

  percona_data:
    driver: "local"

  atom_uploads:
    driver: "local"

  atom_downloads:
    driver: "local"

networks:

  net_cache:
  net_db:
  net_jobs:
  net_http:
  net_search:

services:

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.6.0"
    environment:
      - "bootstrap.memory_lock=true"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms640m -Xmx640m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - "elasticsearch_data:/usr/share/elasticsearch/data"
    networks:
      - "net_search"

  percona:
    image: "percona:5.6"
    environment:
      - "MYSQL_ROOT_PASSWORD=my-secret-pw"
      - "MYSQL_DATABASE=atom"
      - "MYSQL_USER=atom"
      - "MYSQL_PASSWORD=atom_12345"
    volumes:
      - "percona_data:/var/lib/mysql:rw"
      - "./etc/mysql/conf.d/:/etc/mysql/conf.d:ro"
    expose:
      - "3306"
    networks:
      - "net_db"

  memcached:
    image: "memcached"
    command: "-p 11211 -m 128 -u memcache"
    expose:
      - "11211"
    networks:
      - "net_cache"
      - "net_jobs"

  gearmand:
    image: "artefactual/gearmand"
    expose:
      - "4730"
    networks:
      - "net_cache"
      - "net_jobs"

  atom:
    build:
      context: "../"
      dockerfile: "./docker/Dockerfile"
    command: "fpm"
    volumes:
      - "../:/atom/src:rw"
      - "atom_uploads:/atom/src/uploads:rw"
      - "atom_downloads:/atom/src/downloads:rw"
    networks:
      - "net_cache"
      - "net_db"
      - "net_http"
      - "net_jobs"
      - "net_search"
    environment:
      - "ATOM_DEVELOPMENT_MODE=on"
      - "ATOM_ELASTICSEARCH_HOST=elasticsearch"
      - "ATOM_MEMCACHED_HOST=memcached"
      - "ATOM_GEARMAND_HOST=gearmand"
      - "ATOM_MYSQL_DSN=mysql:host=percona;port=3306;dbname=atom;charset=utf8"
      - "ATOM_MYSQL_USERNAME=atom"
      - "ATOM_MYSQL_PASSWORD=atom_12345"

  atom_worker:
    build:
      context: "../"
      dockerfile: "./docker/Dockerfile"
    command: "worker"
    volumes:
      - "../:/atom/src:rw"
      - "atom_uploads:/atom/src/uploads:rw"
      - "atom_downloads:/atom/src/downloads:rw"
    networks:
      - "net_cache"
      - "net_db"
      - "net_jobs"
      - "net_search"
    environment:
      - "ATOM_DEVELOPMENT_MODE=on"
      - "ATOM_ELASTICSEARCH_HOST=elasticsearch"
      - "ATOM_MEMCACHED_HOST=memcached"
      - "ATOM_GEARMAND_HOST=gearmand"
      - "ATOM_MYSQL_DSN=mysql:host=percona;port=3306;dbname=atom;charset=utf8"
      - "ATOM_MYSQL_USERNAME=atom"
      - "ATOM_MYSQL_PASSWORD=atom_12345"

  nginx:
    image: "nginx:latest"
    ports:
      - "80"
    volumes:
      - "../:/atom/src:ro"
      - "./etc/nginx/prod.conf:/etc/nginx/nginx.conf:ro"
      - "atom_uploads:/atom/src/uploads:ro"
      - "atom_downloads:/atom/src/downloads:ro"
    networks:
      - "net_http"
    depends_on:
      - "atom"
